# Generated by Django 4.2.7 on 2024-02-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('fix_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='base_price',
        ),
        migrations.AlterField(
            model_name='pricing',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costAPI.zone'),
        ),
    ]
